= API SERVER Documentation
=======================
:Author: Frederick M. Muriithi
:Email: fredmanglis@gmail.com
:Date: June 2017
:Revision: v0.0.1

== Introduction

The https://arvados.org[Arvados] API Server seems to be the glue that binds the various services together, enabling authentication to happen, data to be stored and retrieved, and computations to be done.

The focus here is on storage and retrieval of data in link:keepstore.asciidoc[Keepstore], so this document will hold data on how to configure the API Server for that.

There will also be need to authenticate the users of the system, meaning documentation on how to do that will also be present.

== Installation and Configuration

The installation process that is currently being considered is that documented at http://doc.arvados.org/install/install-api-server.html[the Arvados wiki]. The page contains information on how to configure most parts of the API server.

=== Informing the API Server of Available Keepstore Servers

This is being investigated at this time.

=== Configuring Authentication

See link:arvados-sso-server.asciidoc[arvados-sso-server].

=== Informing API Server of Keepstore Servers

To inform the API Server of available keepstore servers, you simply enter a record in the `keep_services` table in the _arvados_production_ database.
The record _MUST_ have the following fields:

.Database Fields
[format="csv",cols="3",options="header"]
|====
FIELD,DEFINITION,REQUIRED
uuid,The uuid of the new service. It is composed of 3 parts, in a pattern like the following 'xxxxx-xxxxx-xxxxxxxxxxxxxxx'. The first field of 5 characters is the 'uuid_prefix' that was set up as defined in http://doc.arvados.org/install/install-manual-prerequisites.html[the prerequisites] for the installation.,Y
owner_uuid,The uuid of the user that added the keepstore server.,Y
modified_by_client_uuid,The uuid of client used to add the keepstore server to the database.,N
modified_by_user_uuid,The uuid of the last user to modify the database entry.,N
modified_at,Timestamp of the last modification time.,N
service_host,The url at which the service can be reached.,N
service_port,The port the service is running at.,N
service_ssl_flag,Whether or not ssl is in use.,N
service_type,Whether it is disk or cloud storage or any other (find out more),Y
created_at,Date and time the entry was made,Y
updated_at,Date and time the entry was updated last,Y
read_only,Whether or not the keepstore service is readonly,Y
|====
	
== References

* http://doc.arvados.org/api/index.html[API References]
